# 指定要编译的目标模块
MODULE_NAME := pdc
obj-m := $(MODULE_NAME).o

# 定义要编译的目标模块对象文件
$(MODULE_NAME)-objs := 	src/pdc_init.o \
						src/core/pdc_core.o


# $(MODULE_NAME)-objs += 	src/cpld/pdc_cpld_master.o \
						src/cpld/pdc_cpld_i2c_driver.o


# $(MODULE_NAME)-objs += 	src/lcd/pdc_lcd_master.o \
						src/lcd/pdc_lcd_i2c_driver.o

# $(MODULE_NAME)-objs += 	src/led/pdc_led_master.o \
						src/led/pdc_led_gpio_driver.o

# 添加头文件路径
ccflags-y += 	-I$(src)/include

# 指定额外的头文件和符号表文件
# OSA_DIR := $(src)/../osa
# KBUILD_EXTRA_SYMBOLS := $(OSA_DIR)/Module.symvers
# ccflags-y += 	-I$(OSA_DIR)/include
